name: Server tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      test_db:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_database
        ports:
          - 5433:5432
      test_redis:
        image: redis
        ports:
          - 6380:6379
        options: --entrypoint "redis-server --requirepass test_password"

    steps:
      - uses: actions/checkout@v3.5.2
      
      - name: Use Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.0.0
      
      - name: Install Docker Compose
        run: |
          sudo rm /usr/local/bin/docker-compose
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` > docker-compose
          chmod +x docker-compose
          sudo mv docker-compose /usr/local/bin

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test
        env:
          NODE_ENV: test
          REDIS_HOST: localhost
          REDIS_PORT: 6380
          REDIS_PASSWORD: test_password
          DATABASE_HOST: localhost
          DATABASE_PORT: 5433
          DATABASE_USER: test_user
          DATABASE_PASSWORD: test_password
          DATABASE_NAME: test_database
